@Library('pipeline-lib') _

pipeline {
    agent any

    environment {
        SOLUTION_DIR = 'services/helios.identity'
        DIR = 'services/helios.identity/helios.identity.data'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Load secrets') {
            steps {
                dir("services/helios.identity/helios.identity.api") {
                    loadAppsettings('helios.identity.api', 'Development')
                }
            }
        }

        stage('Database Migrations Dev') {
            steps {
                dir("${SOLUTION_DIR}") {
                    sh """
                    docker run --rm \
                    -v "\$WORKSPACE:/workspace" \
                    -w /workspace \
                    mcr.microsoft.com/dotnet/sdk:9.0 \
                    bash -c "dotnet tool install --global dotnet-ef --version 9.0.0-* && \
                            export PATH=\\\$PATH:/root/.dotnet/tools && \
                            dotnet ef database update \
                            -s ./helios.identity.api \
                            -p ./services/helios.identity/helios.identity.data \
                            -c IdentityContext -- --environment Development"
                    """
                }
            }
        }
    }
}
