@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'FORCE_RUN',
            defaultValue: false,
            description: 'Forces run even if there are no changes'
        )
    }

    environment {
        SOLUTION_DIR = 'services/helios.identity'
        DIR = 'services/helios.identity/helios.identity.data'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Database Migrations Dev') {
            when {
                anyOf {
                    changeset "${DIR}/**"
                    expression { return params.FORCE_RUN }
                }
            }
            agent {
                docker {
                    image 'mcr.microsoft.com/dotnet/sdk:8.0'
                    args '-v $WORKSPACE:/workspace -w /workspace'
                }
            }
            steps {
                dir("${SOLUTION_DIR}") {
                    script {
                        sh 'dotnet ef database update -s ./helios.identity.api -p ./helios.identity.data -c IdentityContext -- --environment Development'
                    }
                }
            }
        }
    }
}
