@Library('pipeline-lib') _

pipeline {
    agent any

    environment {
        SOLUTION_DIR = 'services/helios.identity'
        DIR = 'services/helios.identity/helios.identity.data'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Load secrets') {
            steps {
                dir("services/helios.identity/helios.identity.api") {
                    loadAppsettings('helios.identity.api', 'Development')
                }
            }
        }

        stage('Database Migrations Dev') {
            steps {
                dir("${SOLUTION_DIR}") {
                    updateDBFromMigration('helios.identity', 'IdentityContext', '9.0', '9.0.0-*')
                }
            }
        }
    }
}
