@Library('pipeline-lib') _

pipeline {
    agent any

	environment {
        // relative path from repo root to this microservice
        SERVICE_DIR = 'services/helios.identity/helios.identity.api'
        PUBLISH_DIR = "${SERVICE_DIR}/publish"
    }

    parameters {
        booleanParam(
            name: 'FORCE_RUN',
            defaultValue: false,
            description: 'Forces run even if there are no changes'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            when {
                anyOf {
                    changeset '/src/**'
                    changeset '/package.json'
                    changeset '/package-lock.json'
                    changeset 'Jenkinsfile'
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                sh 'dotnet restore services/helios.identity/helios.identity.sln'
				sh 'dotnet build services/helios.identity/helios.identity.sln -c Release'
            }
        }

        stage('Build') {
            when {
                anyOf {
                    changeset '/src/**'
                    changeset '/package.json'
                    changeset '/package-lock.json'
                    changeset 'Jenkinsfile'
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
            	sh 'npm run build'
            }
        }

        stage('Deploy') {
            when {
                anyOf {
                    changeset '/src/**'
                    changeset '/package.json'
                    changeset '/package-lock.json'
                    changeset 'Jenkinsfile'
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                withCredentials([
					string(credentialsId: 'vps-username', variable: 'USERNAME'),
					string(credentialsId: 'vps-domain', variable: 'DOMAIN')
				]) {
					scpBuildFilesToWWW(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
					updateNginxConf(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
				}
            }
        }
    }
}
