@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'FORCE_RUN',
            defaultValue: false,
            description: 'Forces run even if there are no changes'
        )
    }

    environment {
        SOLUTION_DIR = 'services/helios.identity'
        DIR = 'services/helios.identity/helios.identity.api'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            when {
                anyOf {
                    changeset "${DIR}/**"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                dir("${SOLUTION_DIR}") {
                    script {
                        def imageName = "helios-identity"
                        def imageTag = "latest"   // or BUILD_NUMBER, git commit hash, etc.

                        echo "Building Docker image for ${DIR}..."
                        sh "pwd"
                        
                        sh """
                        docker build \
                            -f ./helios.identity.api/Dockerfile \
                            -t ${imageName}:${imageTag} \
                            .
                        """
                    }
                }
            }
        }

        // stage('Build') {
        //     when {
        //         anyOf {
        //             changeset "${DIR}"
        //             expression { return params.FORCE_RUN }
        //         }
        //     }
        //     steps {
        //         sh 'npm run build'
        //     }
        // }

        // stage('Deploy') {
        //     when {
        //         anyOf {
        //             changeset "${DIR}"
        //             expression { return params.FORCE_RUN }
        //         }
        //     }
        //     steps {
        //         withCredentials([
        //             string(credentialsId: 'vps-username', variable: 'USERNAME'),
        //             string(credentialsId: 'vps-domain', variable: 'DOMAIN')
        //         ]) {
        //             scpBuildFilesToWWW(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
        //             updateNginxConf(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
        //         }
        //     }
        // }
    }
}
