@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'All',
            defaultValue: false,
            description: 'Runs all steps'
        )
		
		booleanParam(
			name: 'Dev',
			defaultValue: false,
			description: 'Runs dev steps'
		)

		booleanParam(
			name: 'Prod',
			defaultValue: false,
			description: 'Runs prod steps'
		)

		booleanParam(
			name: 'Deploy',
			defaultValue: true,
			description: 'Runs deploy steps'
		)
    }

    environment {
        SOLUTION_DIR = 'services/helios.identity'
        DIR = 'services/helios.identity/helios.identity.api'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Load secrets') {
            when { 
				sexpression { return params.All || params.Dev || params.Prod }	
			}
			steps {
                dir("${DIR}") {
                    loadAppsettings('helios.identity.api', 'Development')
                    loadAppsettings('helios.identity.api', 'Production')
                }
            }
        }

        stage('Build Docker Image') {
            when {
				anyOf {
					expression { return params.All || params.Dev || params.Prod }	
				}
			}
			steps {
                dir("${SOLUTION_DIR}") {
                    echo "Building Docker image for ${DIR}..."
                    buildDockerImage('./helios.identity.api/Dockerfile', 'helios-identity', 'latest')
                }
            }
        }

        // DO THIS WHEN MULTIPLE SERVERS ARE PRESENT, ALSO FIND BETTER METHOD
        // stage('Transfer docker image'){}

        stage('Deploy Dev') {
            steps {
				dir("${DIR}") { 
					sh 'scp docker-compose.yml miller@sys1.clarkmiller.ca:/home/miller/helios-identity'
                	sh 'ssh miller@sys1.clarkmiller.ca "cd helios-identity && docker compose up -d"'
				}
            }
        }
    }
}
