@Library('pipeline-lib') _

def serviceDir = sh(script: "dirname ${env.JENKINSFILE}", returnStdout: true).trim()

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'FORCE_RUN',
            defaultValue: false,
            description: 'Forces run even if there are no changes'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            when {
                anyOf {
                    changeset "${serviceDir}src/**"
                    changeset "${serviceDir}package.json"
                    changeset "${serviceDir}package-lock.json"
                    changeset "${serviceDir}Jenkinsfile"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            when {
                anyOf {
                    changeset "${serviceDir}src/**"
                    changeset "${serviceDir}package.json"
                    changeset "${serviceDir}package-lock.json"
                    changeset "${serviceDir}Jenkinsfile"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
            	sh 'npm run build'
            }
        }

        stage('Deploy') {
            when {
                anyOf {
                    changeset "${serviceDir}src/**"
                    changeset "${serviceDir}package.json"
                    changeset "${serviceDir}package-lock.json"
                    changeset "${serviceDir}Jenkinsfile"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                withCredentials([
					string(credentialsId: 'vps-username', variable: 'USERNAME'),
					string(credentialsId: 'vps-domain', variable: 'DOMAIN')
				]) {
					scpBuildFilesToWWW(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
					updateNginxConf(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
				}
            }
        }
    }
}
