@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'FORCE_RUN',
            defaultValue: false,
            description: 'Forces run even if there are no changes'
        )
        booleanParam(
            name: 'FORCE_RUN_DEV',
            defaultValue: false,
            description: 'Forces run prod even if there are no changes'
        )
        booleanParam(
            name: 'FORCE_RUN_PROD',
            defaultValue: false,
            description: 'Forces run prod even if there are no changes'
        )
        booleanParam(
            name: 'FORCE_RUN_UPDATE_NGINX_DEV',
            defaultValue: false,
            description: 'Forces run for update nginx dev step even if there are no changes'
        )
        booleanParam(
            name: 'FORCE_RUN_UPDATE_NGINX_PROD',
            defaultValue: false,
            description: 'Forces run for update nginx prod step even if there are no changes'
        )
    }

    environment {
        DIR = 'services/helios.identity/helios.identity.client'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm

                script {
                    def hasChanges = params.FORCE_RUN || checkMicroservice("${DIR}")

                    if (!hasChanges) {
                        echo "No changes detected in ${DIR}. Exiting pipeline early."
                        currentBuild.result = 'SUCCESS'
                        return // Stops the pipeline from executing further stages
                    }
                }
            }
        }

        stage('Install Dependencies') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                dir("${DIR}") { 
                    sh 'npm install'
                }
            }
        }

 
        stage('Build') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                dir("${DIR}") {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy Dev') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    expression { return params.FORCE_RUN }
                    expression { return params.FORCE_RUN_DEV }
                }
            }
            steps {
                dir("${DIR}") {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, 'dev.helios-identity.qrcool.ca')
                }
            }
        }

        stage('Update Nginx Dev') {
             when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    expression { return params.FORCE_RUN || params.FORCE_RUN_UPDATE_NGINX_DEV }
                }
            }

            steps {
                dir("${DIR}") {
                    updateNginxConf(USERNAME, DOMAIN, 'dev.helios-identity.qrcool.ca', 'nginx.dev.conf')
                }
            }
        }

        stage('Deploy Prod') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    expression { return params.FORCE_RUN }
                    expression { return params.FORCE_RUN_PROD }
                }
            }
            steps {
                dir("${DIR}") {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
                }
            }
        }

        stage('Update Nginx Prod') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    expression { return params.FORCE_RUN || params.FORCE_RUN_UPDATE_NGINX_PROD }
                }
            }
            steps {
                dir("${DIR}") {
                    updateNginxConf(USERNAME, DOMAIN, 'helios-identity.qrcool.ca', 'nginx.prod.conf')
                }
            }
        }
    }
}
