@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'FORCE_RUN',
            defaultValue: false,
            description: 'Forces run even if there are no changes'
        )
    }

    environment {
        DIR = 'services/helios.identity/helios.identity.client'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm

                echo "WORKING DIR: ${DIR}"
            }
        }

        stage('Install Dependencies') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    changeset "${DIR}/Jenkinsfile"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                dir("${DIR}") { 
                    sh 'npm install'
                }
            }
        }

 
        stage('Build') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    changeset "${DIR}/Jenkinsfile"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                dir("${DIR}") {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy') {
            when {
                anyOf {
                    changeset "${DIR}/src/**"
                    changeset "${DIR}/package.json"
                    changeset "${DIR}/package-lock.json"
                    changeset "${DIR}/Jenkinsfile"
                    expression { return params.FORCE_RUN }
                }
            }
            steps {
                dir("${DIR}") {
                    scpBuildFilesToWWW(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
                    updateNginxConf(USERNAME, DOMAIN, 'helios-identity.qrcool.ca')
                }
            }
        }
    }
}
