@Library('pipeline-lib') _

multiServicePipeline(
    pipelines: [
        'helios.services.identity.api': 'services/helios.identity/helios.identity.api',
        'helios.services.identity.client': 'services/helios.identity/helios.identity.client',
        'helios.services.identity.data': 'services/helios.identity/helios.identity.data',
        'helios.services.identity.sdk': 'services/helios.identity/helios.identity.sdk/js'
    ]
)